### ISSUE TITLE
Some way to compare dictionary pages "by reference"

### ISSUE THREAD

**Issue by jhorstmann** [jorgecarleitao/parquet2#167]
I'm working on more efficiently reading dictionary encoded data from parquet into arrow dictionary arrays. This requires some way to quickly check, while processing a stream of pages, whether the dictionary page referenced is still the same. Currently I'm using the following hack of comparing the pointer address of a `&dyn DictPage` (as `usize` to avoid manually implementing `Send`/`Sync` and to make clear this never gets dereferenced).

```rust
let dict_page: &dyn DictPage = ...;
let dict_page_address = dict_page as *const dyn DictPage as *const () as usize;
if self.dict_page_address != dict_page_address {
    // update dictionary mapping
}
```

This seems very fragile, as the allocator could reuse the address directly after freeing a previous dictionary page. If the pages knew their own "identity", like their offset in the original file, this would be much easier.

**Comment by jorgecarleitao** [comment]
Hey @jhorstmann ! :D

If I understood the issue correctly, the relevant note is that in parquet I _think_ that there can be only one dictionary page per column chunk. So, if there is a dictionary, it is always the same.

This question is probably related to a poor design in parquet2 whereby every data page gets a "Arc<dyn DictPage>` and you can't really conclude whether it is the same or not (and use its address).

I agree. -.- and I think that this has been mitigated with https://github.com/jorgecarleitao/parquet2/pull/160. The idea is that the page reader now outputs

```rust
/// A decompressed, encoded page
enum Page {
    Dict(DictHeader, Vec<u8>) // not exactly this layout, but roughly what it contains
    Data(DataHeader, Vec<u8>) // not exactly this layout, but roughly what it contains
}
```

we can technically yield a second dictionary if the file contains more than one (but I think it is against the spec).

if you are using files with multiple dictionaries (I do not see a technical reason for not supporting that in parquet), under the latest main, my first though would be to hash `(DictHeader, Vec<u8>)` and compare hashes. IMO this works because dictionary pages are always plain-encoded and plain encoding preserves semantic equality (which is not true for DataPages whereby a non-deterministic encoder could different bytes from two semantically equal columns.

**Comment by jhorstmann** [comment]
Thanks @jorgecarleitao for your input. Only one dictionary page per chunk is also my understanding. The problem is probably more with the way my code is structured, which is mostly dealing with a stream of pages without associating them to their column chunk. I will look into keeping track of the corresponding column chunk index.

Hashing could also work, but it's probably very unlikely that two chunks have the exact same dictionary in the same order.

With the changes from #160 I might also be able to keep a global counter that gets incremented each time a dictionary is decoded and store that with the decoded dictionary.
